src/v1/RF/RF/Controllers/PartialController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace RF.Controllers
{
    /// <summary>
    /// 分部视图
    /// </summary>
    [AllowAnonymous]
    public class PartialController : Controller
    {
        #region 操作按钮权控

        public ActionResult Action_BuildButton()
        {
            try
            {
                //获取 菜单、按钮、角色权限 
                DataTable dt_menu = DAL.PartialDAL.GetSysMenu();
                DataTable dt_button = DAL.PartialDAL.GetSysButton();
                DataRow dr_role = DAL.PartialDAL.GetSysRole();

                //根据角色权限 生成 菜单页面按钮
                string current_url = Request.Url.AbsolutePath;
                DataRow[] dr_menu = dt_menu.Select("m_url='" + current_url.OfSql() + "'");
                if (dr_menu.Count() == 0)
                {
                    return new EmptyResult();
                }
                else
                {
                    try
                    {
                        //角色权限
                        JObject jo_role = JObject.Parse(dr_role["r_buttons"].ToString());
                        //根据菜单id取对应的按钮id
                        string btns = jo_role[dr_menu[0]["id"].ToString()].ToTokenString();
                        if (btns != "")
                        {
                            DataRow[] dr_button = dt_button.Select("id in(" + btns + ")");
                            List<Model.sys_button> listBtn = new List<Model.sys_button>();
                            foreach (DataRow dr in dr_button)
                            {
                                listBtn.Add(new DAL.sys_button().DataRowToModel(dr));
                            }
                            return PartialView(listBtn);
                        }
                        return new EmptyResult();
                    }
                    catch (Exception)
                    {
                        return new EmptyResult();
                    }
                }
            }
            catch (Exception)
            {
                System.Web.Security.FormsAuthentication.SignOut();
                return new EmptyResult();
            }
        }

        #endregion

        #region 表单生成

        /// <summary>
        /// 表单生成
        /// </summary>
        /// <param name="vname">虚拟表名</param>
        /// <param name="modalsize">模态大小，1：小  2：大 默认2</param>
        /// <returns></returns>
        public ActionResult Action_BuildForm(string vname, string modalsize = "2")
        {
            try
            {
                //虚拟表名
                vname = vname.OfSql();
                DataTable dtC = DB.HelperSQLite.Query("select * from sys_column where vname='" + vname + "' order by f_area,f_order").Tables[0];

                //分区域的 集合
                Dictionary<int, List<RF.Model.sys_column>> dic = new Dictionary<int, List<Model.sys_column>>();

                //按区域分组
                IEnumerable<IGrouping<int, DataRow>> igs = dtC.Rows.Cast<DataRow>().GroupBy<DataRow, int>(d => d["f_area"].Equals(DBNull.Value) ? 1 : Convert.ToInt32(d["f_area"]));
                foreach (IGrouping<int, DataRow> ig in igs)
                {
                    List<RF.Model.sys_column> listC = new List<Model.sys_column>();
                    foreach (DataRow dr in ig)
                    {
                        listC.Add(new DAL.sys_column().DataRowToModel(dr));
                    }
                    dic.Add(Convert.ToInt32(ig.First()["f_area"].Equals(DBNull.Value) ? 1 : ig.First()["f_area"]), listC);
                }

                //ID索引
                int index = string.IsNullOrEmpty(Request["index"]) ? 1 : Convert.ToInt32(Request["index"]);
                ViewBag.index = index;
                ViewBag.modalsize = modalsize == "2" ? "modal-lg" : "";
                return PartialView(dic);
            }
            catch (Exception)
            {
                return new EmptyResult();
            }
        }
        #endregion

        #region 配置表格

        /// <summary>
        /// 保存表格配置
        /// </summary>
        /// <returns></returns>
        public string SaveTableConfig()
        {
            string vname = Request["vname"].ToString();
            string rows = Request["rows"].ToString();
            JArray ja = JArray.Parse(rows);
            StringBuilder sb = new StringBuilder();
            int order = 0;
            foreach (JToken jt in ja)
            {
                string title = jt["title"].ToTokenString();
                int id, width, align, hide, frozen;
                id = Convert.ToInt32(jt["id"].ToTokenString());
                if (!int.TryParse(jt["width"].ToTokenString(), out width))
                {
                    width = 0;
                }
                if (!int.TryParse(jt["align"].ToTokenString(), out align))
                {
                    align = 1;
                }
                if (!int.TryParse(jt["hide"].ToTokenString(), out hide))
                {
                    hide = 0;
                }
                if (!int.TryParse(jt["frozen"].ToTokenString(), out frozen))
                {
                    frozen = 0;
                }
                order++;
                sb.AppendFormat("update sys_column set title='{0}',width={1},align={2},hide={3},frozen={4},l_order={5} where id={6} and vname='{7}';", title.OfSql(), width, align, hide, frozen, order, id, vname.OfSql());
            }
            int n = DB.HelperSQLite.ExecuteSql(sb.ToString());
            return n >= 0 ? "success" : "fail";
        }

        #endregion

        #region 配置表单
        public string SaveFormConfig()
        {
            string vname = Request["vname"].ToString().OfSql();
            string rows = Request["rows"].ToString();
            JArray ja = JArray.Parse(rows);
            StringBuilder sb = new StringBuilder();
            int order = 1;
            foreach (JToken jt in ja)
            {
                string title = jt["title"].ToTokenString().OfSql();
                string field = jt["field"].ToTokenString().OfSql();
                int col, area;
                if (!int.TryParse(jt["col"].ToTokenString(), out col))
                {
                    col = 1;
                }
                if (!int.TryParse(jt["area"].ToTokenString(), out area))
                {
                    area = 1;
                }
                sb.AppendFormat("update sys_column set title='{0}',f_col={1},f_area={2},f_order={3} where field='{4}' and vname='{5}';", title, col, area, order, field, vname);
                order++;
            }
            int n = DB.HelperSQLite.ExecuteSql(sb.ToString());
            return n >= 0 ? "success" : "fail";
        }
        #endregion

        #region 数据库重置

        /// <summary>
        /// 重置站点数据库
        /// </summary>
        /// <returns></returns>
        public string SiteReset()
        {
            string result = string.Empty;
            string app_data = Server.MapPath("/App_Data/");
            try
            {
                System.IO.File.Copy(app_data + "_sqlite.db", app_data + "sqlite.db", true);
                result = "success";
            }
            catch (Exception)
            {
                result = "fail";
            }
            return result;
        }

        #endregion
    }
}

src/v1/RF/RF/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RF.Controllers
{
    /// <summary>
    /// 系统管理
    /// </summary>
    public class SettingController : Controller
    {
        #region 系统角色

        public ActionResult SysRole()
        {
            //菜单导航
            ViewBag.MenuTreeJson = new CommonController().QueryMenuTree();

            return View();
        }

        /// <summary>
        /// 保存
        /// </summary>
        /// <param name="mo"></param>
        /// <returns></returns>
        public string SaveSysRole(Model.sys_role mo)
        {
            string savetype = Request.QueryString["savetype"].ToString();
            mo.r_state = string.IsNullOrEmpty(Request.Form["r_state"]) ? 0 : 1;

            bool b = false;
            if (savetype == "0")
            {
                if (new DAL.sys_role().Add(mo) >= 0)
                    b = true;
            }
            else
            {
                mo.id = Convert.ToInt32(savetype);
                b = new DAL.sys_role().Update(mo);
            }
            return b ? "success" : "fail";
        }

        /// <summary>
        /// 保存角色权限配置
        /// </summary>
        /// <returns></returns>
        public string SaveSysRoleAuth()
        {
            int id = Convert.ToInt32(Request.QueryString["id"]);
            string menus = Request.Form["r_menus"];
            string buttons = Request.Form["r_buttons"];
            bool b = DAL.SettingDAL.SaveSysRoleAuth(id, menus, buttons);
            return b ? "success" : "fail";
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <returns></returns>
        public string DelSysRole()
        {
            int id = Convert.ToInt32(Request.QueryString["id"]);
            bool b = new DAL.sys_role().Delete(id);
            return b ? "success" : "fail";
        }

        #endregion

        #region 系统用户

        public ActionResult SysUser()
        {
            return View();
        }

        /// <summary>
        /// 保存
        /// </summary>
        /// <param name="mo"></param>
        /// <returns></returns>
        public string SaveSysUser(Model.sys_user mo)
        {
            string savetype = Request.QueryString["savetype"].ToString();
            mo.u_state = string.IsNullOrEmpty(Request.Form["u_state"]) ? 0 : 1;

            bool b = false;
            if (savetype == "0")
            {
                mo.id = Guid.NewGuid().ToString();
                mo.u_date = DateTime.Now;
                mo.u_pwd = DB.CalcTo.MD5(mo.u_pwd);
                b = new DAL.sys_user().Add(mo);
            }
            else
            {
                mo.id = savetype;
                if (mo.u_pwd.Length != 32)
                {
                    mo.u_pwd = DB.CalcTo.MD5(mo.u_pwd);
                }
                b = new DAL.sys_user().Update(mo);
            }
            return b ? "success" : "fail";
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <returns></returns>
        public string DelSysUser()
        {
            string id = Request.QueryString["id"].ToString();
            bool b = new DAL.sys_user().Delete(id);
            return b ? "success" : "fail";
        }

        #endregion

        #region 系统日志

        public ActionResult SysLog()
        {
            return View();
        }

        #endregion

        #region 列表配置

        public ActionResult SysColumn()
        {
            return View();
        }

        /// <summary>
        /// 保存 列配置
        /// </summary>
        /// <param name="col"></param>
        /// <returns></returns>
        public string SaveSysColumn(Model.sys_column mo)
        {
            bool b = false;
            string savetype = Request.QueryString["savetype"].ToString();

            //新增
            if (savetype == "0")
            {
                if (new DAL.sys_column().Add(mo) > 0)
                    b = true;
            }
            else
            {
                b = new DAL.sys_column().Update(mo);
            }

            return b ? "success" : "fail";
        }


        /// <summary>
        /// 删除 列配置
        /// </summary>
        /// <returns></returns>
        public string DelSysColumn()
        {
            int id = Convert.ToInt32(RouteData.Values["Id"]);
            bool b = new DAL.sys_column().Delete(id);
            return b ? "success" : "fail";
        }

        #endregion

        #region 字体配置

        public ActionResult SysStyleConfig()
        {
            return View();
        }

        #endregion
    }
}

src/v1/RF/RF/Views/Setting/SysColumn.cshtml
@{
    ViewBag.Title = "列表配置";
}

<!--搜索区域-->
<div class="row">
    <div class="col-md-6">

        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="搜索：表名、字段名" id="txtSearch">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="button" id="btnSearch">
                        <i class="fa fa-search"></i>&nbsp;搜索
                    </button>
                </span>
            </div>
        </div>

    </div>
</div>

<div id="Grid1"></div>

@{Html.RenderAction("Action_BuildForm", "Partial", new { vname = "sys_column", modalsize = "2" });}

<script src="/Scripts/z.js"></script>

<script>

    var gd1 = z.Grid();
    gd1.pageSize = 100;
    gd1.url = "/Common/QueryData?uri=ppcolumn";
    gd1.post = {
        keywords: function () { return $('#txtSearch').val() }
    };
    gd1.load();

    //刷新
    z.button('reload', function () {
        gd1.load();
    });
    $('#btnSearch').click(function () {
        gd1.load();
    });
    $('#txtSearch').keydown(function (e) {
        e = e || window.event;
        if ((e.keyCode || e.which || e.charCode) == 13) {
            gd1.load();
        }
    });

    //对齐方式
    z.DC["ls_align"] = [{ "id": 1, "text": "居左" }, { "id": 2, "text": "居中" }, { "id": 3, "text": "居右" }];
    //格式化
    z.DC["ls_format"] = [
        { id: "", text: "无格式化", selected: true },
        { id: "col_custom_", text: "col_custom_开头 + field" },
        { id: "11", text: "yyyy-MM" },
        { id: "12", text: "HH:mm:ss" },
        { id: "13", text: "yyyy-MM-dd HH:mm:ss" },
        { id: "14", text: "yyyy-MM-dd" },
        { id: "15", text: "精确两位" },
        { id: "16", text: "确两位 带￥" },
        { id: "17", text: "1√ 0×" },
        { id: "18", text: "1× 0√" },
        { id: "19", text: "1正常 0停用" },
        { id: "20", text: "2居中 3居右" },
        { id: "21", text: "1 隐藏列" },
        { id: "22", text: "1 冻结列" }
    ];
    //表单类型
    z.DC["ls_f_type"] = [
        { id: "text", text: "text 文本" },
        { id: "date", text: "yyyy-MM-dd 日期" },
        { id: "time", text: "mm:ss 时间" },
        { id: "datetime", text: "yyyy-MM-dd HH:mm:ss 日期时间" },
        { id: "calc", text: "calc 计算器" },
        { id: "combobox", text: "combobox 下拉列表框" },
        { id: "combotree", text: "combotree 下拉列表树" },
        { id: "modal", text: "modal 模态弹出（浏览）" },
        { id: "checkbox", text: "checkbox 复选框" },
        { id: "password", text: "password 密码框" }
    ];
    //区域
    z.DC["ls_f_area"] = [
        { id: 1, text: "表格配置", selected: true },
        { id: 2, text: "表单配置" }
    ];
    //表单跨列
    z.DC["ls_f_col"] = [
        { id: 1, text: "一半排", selected: true },
        { id: 2, text: "一整排" }
    ];

    //表格配置
    z.DC["TableN"] = { vname: "sys_column" };

    //表单配置 表单ID索引，区域标题，配置对象
    z.DC["FormN"] = [{ index: 1, areas: z.DC["ls_f_area"], active: true, vname: "sys_column" }];


    //新增前 准备
    function addReady() {
        $('#_af_saveadd_1').show();
        $('#_af_save_1').attr('savetype', 0);
        z.RequiredValidation('reset', '#_af_form_1');
        z.FormTitle({
            id: "#_af_title_1",
            icon: 0,
            title: '新增列表配置'
        });
        z.FormClear("#_af_form_1");
        $('#_af_modal_1').modal('show');
    }

    //新增
    z.button('add', function () {
        addReady();
    });

    z.isPC() && gd1.dblclickRowE(UpdateFn);
    z.button('edit', UpdateFn);
    //修改(双击行模拟触发修改按钮点击事件)
    function UpdateFn() {
        z.RequiredValidation('reset', '#_af_form_1');
        $('#_af_saveadd_1').hide();
        var rowData = gd1.row();
        if (rowData) {
            gd1.rowEdit();
            z.FormTitle({
                id: "#_af_title_1",
                icon: 1,
                title: '修改列配置'
            });
            $('#_af_save_1').attr('savetype', rowData.id);
            $('#_af_modal_1').modal('show');
        } else {
            art('select');
        }
    }

    //保存
    function SaveFn() {
        if (z.RequiredValidation('red', '#_af_form_1')) {
            var postData = $("#_af_form_1").serialize(),
                savetype = $('#_af_save_1').attr('savetype');

            $('#_af_save_1')[0].disabled = true;
            $('#_af_saveadd_1')[0].disabled = true;

            $.ajax({
                url: "/Setting/SaveSysColumn?savetype=" + savetype,
                type: "post",
                data: postData,
                success: function (data) {
                    if (data == "success") {
                        if (savetype == 0) {
                            $('#_af_save_1').attr('saveadd') == 1 ? addReady() : $('#_af_modal_1').modal('hide');
                            gd1.F5();
                        } else {
                            gd1.updataRow(z.FormToJson("#_af_form_1"))
                            $('#_af_modal_1').modal('hide');
                        }
                    } else {
                        art('fail');
                    }
                },
                error: function () {
                    art('error');
                }
            });

            $('#_af_save_1')[0].disabled = false;
            $('#_af_saveadd_1')[0].disabled = false;
        }
    }
    $('#_af_save_1').click(function () {
        $('#_af_save_1').attr('saveadd', 0);
        SaveFn();
    });
    $('#_af_saveadd_1').click(function () {
        $('#_af_save_1').attr('saveadd', 1);
        SaveFn();
    });

    //删除
    z.button('del', function () {
        var rowData = gd1.row();
        if (!rowData) {
            art('select');
            return false;
        }
        art('确定删除选中的行', function () {
            $.ajax({
                url: "/Setting/DelSysColumn/" + rowData.id,
                type: "post",
                success: function (data) {
                    if (data == "success") {
                        gd1.F5();
                    } else {
                        art('fail');
                    }
                }
            })
        });
    });
</script>

src/v1/RF/RF/Views/Setting/SysLog.cshtml
@{
    ViewBag.Title = "系统日志";
}

<!--搜索区域-->
<div class="row">
    <div class="col-md-6">

        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="搜索：账号、控制器、IP、操作说明" id="txtSearch">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="button" id="btnSearch">
                        <i class="fa fa-search"></i>&nbsp;搜索
                    </button>
                </span>
            </div>
        </div>

    </div>
</div>

<div id="Grid1"></div>

<script src="/Scripts/z.js"></script>

<script>

    var gd1 = z.Grid();
    gd1.url = "/Common/QueryData?uri=pplog";
    gd1.post = {
        keywords: function () { return $('#txtSearch').val() }
    };
    gd1.load();

    //刷新
    z.button('reload', function () {
        gd1.load();
    });
    $('#btnSearch').click(function () {
        gd1.load();
    });
    $('#txtSearch').keydown(function (e) {
        e = e || window.event;
        if ((e.keyCode || e.which || e.charCode) == 13) {
            gd1.load();
        }
    });

</script>

src/v1/RF/RF/Views/Setting/SysRole.cshtml
@{
    ViewBag.Title = "系统角色";
}

@model RF.Model.sys_role


<div id="Grid1"></div>

@{Html.RenderAction("Action_BuildForm", "Partial", new { vname = "sys_role", modalsize = "1" });}

<!--模态 表单-->
<div class="modal fade" id="myModalPower" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">
                    <i class="fa fa-cog orange fa-2x" style="margin-right:10px;vertical-align:middle"></i>权限设置
                </h4>
            </div>

            <div class="modal-body" style="overflow:auto">
                <!--导航菜单树-->
                <div class="col-md-6 col-sm-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            菜单导航
                        </div>
                        <div class="panel-body" style="height:300px">
                            <ul id="ulMenuTree"></ul>
                        </div>
                    </div>
                </div>
                <!--菜单对应按钮-->
                <div class="col-md-6 col-sm-6">
                    <div id="pGrid2" style="height:341px">
                        <div id="Grid2"></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="btnSavePower" type="button" class="btn btn-primary"><span class="fa fa-save"></span>&nbsp;保存</button>
            </div>
        </div>
    </div>
</div>

<input type="hidden" value="@ViewBag.MenuTreeJson" id="hid_menu" />

<script src="/Scripts/z.js"></script>

<script>

    //菜单、按钮、菜单JSON
    var pMenu = "", pButton = {}, menuJson = $.parseJSON($('#hid_menu').val());

    var gd1 = z.Grid();
    gd1.url = "/Common/QueryData?uri=pprole";
    gd1.load();

    //刷新
    z.button('reload', function () {
        gd1.load();
    });

    //表格配置
    z.DC["TableN"] = { vname: "sys_role" };

    //表单配置 表单ID索引，区域标题，配置对象
    z.DC["FormN"] = [{ index: 1, areas: [], active: true, vname: "sys_role" }];

    //新增前 准备
    function addReady() {
        $('#_af_saveadd_1').show();
        $('#_af_save_1').attr('savetype', 0);
        z.RequiredValidation('reset', '#_af_form_1');
        z.FormTitle({
            id: "#_af_title_1",
            icon: 0,
            title: '新增角色'
        });
        z.FormClear("#_af_form_1");
        $('#_af_modal_1').modal('show');
    }

    //新增
    z.button('add', function () {
        addReady();
    });

    z.isPC() && gd1.dblclickRowE(UpdateFn);
    z.button('edit', UpdateFn);
    //修改(双击行模拟触发修改按钮点击事件)
    function UpdateFn() {
        z.RequiredValidation('reset', '#_af_form_1');
        $('#_af_saveadd_1').hide();
        var rowData = gd1.row();
        if (rowData) {
            gd1.rowEdit();
            z.FormTitle({
                id: "#_af_title_1",
                icon: 1,
                title: '修改角色'
            });
            $('#_af_save_1').attr('savetype', rowData.id);
            $('#_af_modal_1').modal('show');
        } else {
            art('select');
        }
    }

    //保存
    function SaveFn() {
        if (z.RequiredValidation('red', '#_af_form_1')) {
            var postData = $("#_af_form_1").serialize(),
                savetype = $('#_af_save_1').attr('savetype');

            $('#_af_save_1')[0].disabled = true;
            $('#_af_saveadd_1')[0].disabled = true;

            $.ajax({
                url: "/Setting/SaveSysRole?savetype=" + savetype,
                type: "post",
                data: postData,
                success: function (data) {
                    if (data == "success") {
                        if (savetype == 0) {
                            $('#_af_save_1').attr('saveadd') == 1 ? addReady() : $('#_af_modal_1').modal('hide');
                            gd1.F5();
                        } else {
                            gd1.updataRow(z.FormToJson("#_af_form_1"))
                            $('#_af_modal_1').modal('hide');
                        }
                    } else {
                        art('fail');
                    }
                },
                error: function () {
                    art('error');
                }
            });

            $('#_af_save_1')[0].disabled = false;
            $('#_af_saveadd_1')[0].disabled = false;
        }
    }
    $('#_af_save_1').click(function () {
        $('#_af_save_1').attr('saveadd', 0);
        SaveFn();
    });
    $('#_af_saveadd_1').click(function () {
        $('#_af_save_1').attr('saveadd', 1);
        SaveFn();
    });

    //删除
    z.button('del', function () {
        var rowData = gd1.row();
        if (!rowData) {
            art('select');
            return false;
        }
        art('确定删除选中的行', function () {
            $.ajax({
                url: "/Setting/DelSysRole?id=" + rowData.id,
                type: "post",
                success: function (data) {
                    if (data == "success") {
                        gd1.F5();
                    } else {
                        art('fail');
                    }
                }
            })
        });
    });

    //菜单导航树
    var completeCheck = 0;
    function BindMenuTree(json, ids) {
        completeCheck = 0;
        ids = ids ? ids.split(',') : [];
        $('#ulMenuTree').tree({
            data: json,
            checkbox: true,
            onBeforeSelect: function (node) {
                return node.children == null;
            },
            onCheck: function (node, checked) {
                if (completeCheck) {
                    var mIn = $('#ulMenuTree').tree('getChecked'),
                        mInQ = $('#ulMenuTree').tree('getChecked', 'indeterminate'),
                        mInS = mIn.concat(mInQ),
                        ids = [];
                    $(mInS).each(function () {
                        ids.push(this.id);
                    });
                    pMenu = ids.join(',');
                }
            },
            onSelect: function (node) {
                $(gd2.id).datagrid('unselectAll');
                var btns = pButton[node.id];
                if (btns) {
                    btns = btns.split(',');
                    var rows = gd2.rowAll();
                    $(rows).each(function () {
                        for (var i = 0; i < btns.length; i++) {
                            if (this.id == btns[i]) {
                                var rIndex = $(gd2.id).datagrid('getRowIndex', this);
                                $(gd2.id).datagrid('checkRow', rIndex);
                            }
                        }
                    })
                }
            },
            onLoadSuccess: function () {
                var umt = $('#ulMenuTree'), nodes = umt.tree('getChildren');
                $(nodes).each(function () {
                    for (var i = 0; i < ids.length; i++) {
                        if (this.id == ids[i]) {
                            umt.tree('check', this.target);
                        }
                    }
                });
                completeCheck = 1;
            }
        });
    }


    //菜单按钮
    var gd2 = z.Grid();
    gd2.id = "#Grid2";
    gd2.autosizePid = "#pGrid2";
    gd2.autosize = "p";
    gd2.url = "/Common/QueryData?uri=ppbutton";
    gd2.columnsExists = 1;
    gd2.pageSize = 999;
    gd2.page = false;
    gd2.checkbox = true;
    gd2.single = false;
    gd2.bindBeforeE = function () {
        gd2.columns = [
            { field: "b_title", title: "按钮名称", width: 120 },
            { field: "b_remark", title: "备注说明", width: 120 }
        ];
    }

    //权限设置
    z.button('auth', function () {
        var rowData = gd1.row();
        if (rowData) {
            $('#myModalPower').modal();
            rowData.r_menus && (pMenu = rowData.r_menus);
            rowData.r_buttons && (pButton = $.parseJSON(rowData.r_buttons));
            BindMenuTree(menuJson, pMenu);
        } else {
            art('select');
        }
    });
    $('#myModalPower').on('shown.bs.modal', function () {
        if ($(this).attr('data-init') != 1) {
            $(this).attr('data-init', 1);
            gd2.load();
        } else {
            gd2.F5Local();
        }
    });


    //更新按钮
    $(gd2.autosizePid).mousedown(function () {
        setTimeout(function () {
            var mIn = $('#ulMenuTree').tree('getSelected');
            if (mIn) {
                var rowData = gd2.row(), ids = [];
                if (rowData) {
                    $(rowData).each(function () {
                        ids.push(this.id);
                    });
                }
                pButton[mIn.id] = ids.join(',');
            }
        }, 200);
    });

    //保存菜单及按钮
    $('#btnSavePower').click(function () {
        var obj = { r_menus: pMenu, r_buttons: JSON.stringify(pButton) };
        $.ajax({
            url: '/Setting/SaveSysRoleAuth?id=' + gd1.row().id,
            type: 'post',
            data: obj,
            success: function (data) {
                if (data == "success") {
                    $('#myModalPower').modal('hide');
                    gd1.updataRow(obj);
                } else {
                    art('fail');
                }
            },
            error: function () {
                art('error');
            }
        })
    });
</script>