src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Components/FormViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Netnr.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Netnr.ResponseFramework.Components
{
    public class FormViewComponent : ViewComponent
    {
        /// <summary>
        /// 模态框表单组件
        /// </summary>
        /// <param name="tablename">列配置表名</param>
        /// <param name="paneltitle">面板标题（有两个区域或以上时，英文逗号分隔）</param>
        /// <param name="modalsize">模态框大小 1小 2中 3大</param>
        /// <param name="index">表单ID后缀</param>
        /// <returns></returns>
        public IViewComponentResult Invoke(string tablename, string paneltitle = "", int modalsize = 3, int index = 1)
        {
            using (var db = new ContextBase())
            {
                //查询表对应的表单，排序，按区域分组
                var listCol = db.SysTableConfig.Where(x => x.TableName == tablename).OrderBy(x => x.FormOrder).ToList();

                var groupCol = listCol.GroupBy(x => x.FormArea.Value).ToList();

                //表名
                TempData["tablename"] = tablename;
                //ID索引
                TempData["index"] = index;
                //模态框大小
                TempData["modalsize"] = modalsize == 3 ? "modal-lg" : modalsize == 1 ? "modal-sm" : "";
                //多面板标题
                TempData["paneltitle"] = paneltitle.Split(',').ToList();

                return View(groupCol);
            }
        }
    }
}

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Netnr.Data;
using Netnr.Domain;
using Netnr.Func.ViewModel;

namespace Netnr.ResponseFramework.Controllers
{
    [Authorize]
    public class SettingController : Controller
    {
        #region 系统按钮

        [Description("系统按钮页面")]
        public IActionResult SysButton()
        {
            return View();
        }

        [Description("查询系统按钮")]
        public string QuerySysButton(QueryDataVM.GetParams param)
        {
            var or = new QueryDataVM.OutputResult();
            using (var db = new ContextBase())
            {
                var list = db.SysButton.OrderBy(x => x.BtnOrder).ToList();
                var tree = Func.Common.ListToTree(list, "Pid", "Id", new List<string> { Guid.Empty.ToString() });
                or.data = tree.ToJArray();

                //列
                if (param.columnsExists != 1)
                {
                    or.columns = db.SysTableConfig.Where(x => x.TableName == param.tableName).OrderBy(x => x.ColOrder).ToList();
                }
            }
            return or.ToJson();
        }

        [Description("保存系统按钮")]
        public string SaveSysButton(SysButton mo, string savetype)
        {
            int num = 0;

            if (string.IsNullOrWhiteSpace(mo.Pid))
            {
                mo.Pid = Guid.Empty.ToString();
            }
            using (var db = new ContextBase())
            {
                if (savetype == "add")
                {
                    mo.Id = Guid.NewGuid().ToString();
                    db.SysButton.Add(mo);
                }
                else
                {
                    db.SysButton.Update(mo);
                }
                num = db.SaveChanges();
            }

            //清理缓存
            Core.CacheTo.Remove(Func.Common.GlobalCacheKey.SysButton);

            return num > 0 ? "success" : "fail";
        }

        [Description("删除系统按钮")]
        public string DelSysButton(string id)
        {
            int num = 0;
            using (var db = new ContextBase())
            {
                var mo = db.SysButton.Find(id);
                db.SysButton.Remove(mo);
                num = db.SaveChanges();
            }
            return num > 0 ? "success" : "fail";
        }

        #endregion

        #region 系统菜单

        [Description("系统菜单页面")]
        public IActionResult SysMenu()
        {
            return View();
        }

        [Description("查询系统菜单")]
        public string QuerySysMenu(QueryDataVM.GetParams param)
        {
            var or = new QueryDataVM.OutputResult();
            using (var db = new ContextBase())
            {
                var list = db.SysMenu.OrderBy(x => x.MenuOrder).ToList();
                var tree = Func.Common.ListToTree(list, "Pid", "Id", new List<string> { Guid.Empty.ToString() });
                or.data = tree.ToJArray();

                //列
                if (param.columnsExists != 1)
                {
                    or.columns = db.SysTableConfig.Where(x => x.TableName == param.tableName).OrderBy(x => x.ColOrder).ToList();
                }
            }
            return or.ToJson();
        }

        [Description("保存系统菜单")]
        public string SaveSysMenu(SysMenu mo, string savetype)
        {
            int num = 0;
            if (string.IsNullOrWhiteSpace(mo.Pid))
            {
                mo.Pid = Guid.Empty.ToString();
            }
            using (var db = new ContextBase())
            {
                if (savetype == "add")
                {
                    mo.Id = Guid.NewGuid().ToString();
                    db.SysMenu.Add(mo);
                }
                else
                {
                    db.SysMenu.Update(mo);
                }
                num = db.SaveChanges();
            }

            //清理缓存
            Core.CacheTo.Remove(Func.Common.GlobalCacheKey.SysMenu);

            return num > 0 ? "success" : "fail";
        }

        [Description("删除系统菜单")]
        public string DelSysMenu(string id)
        {
            int num = 0;
            using (var db = new ContextBase())
            {
                var mo = db.SysMenu.Find(id);
                db.SysMenu.Remove(mo);
                num = db.SaveChanges();
            }
            return num > 0 ? "success" : "fail";
        }

        #endregion

        #region 系统角色

        [Description("系统角色页面")]
        public IActionResult SysRole()
        {
            return View();
        }

        [Description("查询系统角色")]
        public string QuerySysRole(QueryDataVM.GetParams param)
        {
            var or = new QueryDataVM.OutputResult();
            using (var db = new ContextBase())
            {
                var query = db.SysRole;
                Func.Common.QueryJoin(query, param, db, ref or);
            }
            return or.ToJson();
        }

        [Description("保存系统角色")]
        public string SaveSysRole(SysRole mo, string savetype)
        {
            int num = 0;
            using (var db = new ContextBase())
            {
                if (savetype == "add")
                {
                    mo.Id = Guid.Empty.ToString();
                    mo.CreateTime = DateTime.Now;
                    db.SysRole.Add(mo);
                }
                else
                {
                    db.SysRole.Update(mo);
                }
                num = db.SaveChanges();
            }
            return num > 0 ? "success" : "fail";
        }

        [Description("删除系统角色")]
        public string DelSysRole(string id)
        {
            int num = 0;
            using (var db = new ContextBase())
            {
                if (db.SysUser.Where(x => x.RoleId == id).Count() > 0)
                {
                    return "exists";
                }
                else
                {
                    var mo = db.SysRole.Find(id);
                    db.SysRole.Remove(mo);
                    num = db.SaveChanges();
                }
            }
            return num > 0 ? "success" : "fail";
        }

        #endregion

        #region 系统用户

        [Description("系统用户页面")]
        public IActionResult SysUser()
        {
            return View();
        }

        [Description("查询系统用户")]
        public string QuerySysUser(QueryDataVM.GetParams param)
        {
            var or = new QueryDataVM.OutputResult();
            using (var db = new ContextBase())
            {
                var query = from a in db.SysUser
                            join b in db.SysRole on a.RoleId equals b.Id
                            select new
                            {
                                a.Id,
                                a.Nickname,
                                a.RoleId,
                                a.Sign,
                                a.Status,
                                a.UserGroup,
                                a.UserName,
                                a.UserPwd,
                                a.CreateTime,
                                OldUserPwd = a.UserPwd,
                                RoleName = b.Name
                            };
                Func.Common.QueryJoin(query, param, db, ref or);
            }
            return or.ToJson();
        }

        [Description("保存系统用户")]
        public string SaveSysUser(SysUser mo, string savetype, string OldUserPwd)
        {
            int num = 0;
            using (var db = new ContextBase())
            {
                if (savetype == "add")
                {
                    if (db.SysUser.Where(x => x.UserName == mo.UserName).Count() > 0)
                    {
                        return "exists";
                    }
                    mo.Id = Guid.NewGuid().ToString();
                    mo.CreateTime = DateTime.Now;
                    mo.UserPwd = Core.CalcTo.MD5(mo.UserPwd);
                    db.SysUser.Add(mo);
                }
                else
                {
                    if (db.SysUser.Where(x => x.UserName == mo.UserName && x.Id != mo.Id).Count() > 0)
                    {
                        return "exists";
                    }
                    if (mo.UserPwd != OldUserPwd)
                    {
                        mo.UserPwd = Core.CalcTo.MD5(mo.UserPwd);
                    }
                    db.SysUser.Update(mo);
                }
                num = db.SaveChanges();
            }
            return num > 0 ? "success" : "fail";
        }

        [Description("删除系统用户")]
        public string DelSysUser(string id)
        {
            int num = 0;
            using (var db = new ContextBase())
            {
                var mo = db.SysUser.Find(id);
                db.SysUser.Remove(mo);
                num = db.SaveChanges();
            }
            return num > 0 ? "success" : "fail";
        }

        #endregion

        #region 系统日志

        [Description("系统日志页面")]
        public IActionResult SysLog()
        {
            return View();
        }

        [Description("查询系统日志")]
        public string QuerySysLog(QueryDataVM.GetParams param)
        {
            var or = new QueryDataVM.OutputResult();
            using (var db = new ContextBase())
            {
                var query = db.SysLog;
                Func.Common.QueryJoin(query, param, db, ref or);
            }
            return or.ToJson();
        }
        #endregion

        #region 表配置

        [Description("系统表配置页面")]
        public IActionResult SysTableConfig()
        {
            return View();
        }

        [Description("查询表配置")]
        public string QuerySysTableConfig(QueryDataVM.GetParams param)
        {
            var or = new QueryDataVM.OutputResult();

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Setting/SysButton.cshtml
@{
    ViewData["Title"] = "按钮管理";
}

@await Component.InvokeAsync("Form", new { tablename = "sysbutton" })

<partial name="_BaseViewPartial" />

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Setting/SysLog.cshtml
@{
    ViewData["Title"] = "SysLog";
}

@await Component.InvokeAsync("Form", new { tablename = "syslog" })
<partial name="_BaseViewPartial" />

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Setting/SysMenu.cshtml
@{
    ViewData["Title"] = "菜单管理";
}

@await Component.InvokeAsync("Form", new { tablename = "sysmenu" })

<partial name="_BaseViewPartial" />

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Setting/SysRole.cshtml
@{
    ViewData["Title"] = "角色管理";
}

@await Component.InvokeAsync("Form", new { tablename = "sysrole", modalsize = 2 })

<!--模态 表单-->
<div class="modal fade modalautoheight" id="myModalAuth" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">
                    <i class="fa fa-cog orange"></i><span>权限设置</span>
                </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <!--菜单配置-->
                    <div class="col-md-6 col-sm-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">菜单配置（勾选启用）</div>
                            <div class="panel-body modalscroll">
                                <ul id="navTree" style="overflow:hidden"></ul>
                            </div>
                        </div>
                    </div>
                    <!--菜单功能按钮配置-->
                    <div class="col-md-6 col-sm-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">菜单功能按钮配置（勾选启用）</div>
                            <div class="panel-body modalscroll">
                                <ul id="btnTree"></ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="btnSaveAuth" type="button" class="btn btn-primary"><span class="fa fa-save"></span>&nbsp;保存</button>
            </div>
        </div>
    </div>
</div>

<partial name="_BaseViewPartial" />

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Setting/SysStyle.cshtml
@{
    ViewData["Title"] = "样式配置";
}

<div class="container">
    <form class="form-horizontal mt5">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-sm-3 control-label">预览效果</label>
                    <div class="col-sm-8">
                        <p class="form-control-static"> 这是一段样式文字效果演示。<br />说明：切换浏览器后会失效，需重新设置。 </p>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-sm-3 control-label">字体大小</label>
                    <div class="col-sm-8">
                        <select class="form-control" id="seFontSize">
                            <option value="14px">（ 正常 14px ）</option>
                            <option value="16px"> 大（16px） </option>
                            <option value="18px"> 超大（18px） </option>
                            <option value="12px"> 小（12px） </option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-sm-3 control-label">字体类型</label>
                    <div class="col-sm-8">
                        <select class="form-control" id="seFontFamily">
                            <option value="">（ 默认字体 ）</option>
                            <option value="Verdana"> Verdana </option>
                            <option value="Microsoft YaHei"> 微软雅黑 </option>
                            <option value="MS Sans Serif"> MS Sans Serif </option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-sm-3 control-label">功能按钮</label>
                    <div class="col-sm-8">
                        <select class="form-control" id="seButtonStyle">
                            <option value="">（ 默认小清新风格 ）</option>
                            <option value="1"> 深色背景风格 </option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-sm-8 col-sm-offset-3">
                        <button id="btnSaveStyle" type="button" class="btn btn-lg btn-primary btn-block"> 保 存 </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<partial name="_BaseViewPartial" />

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Setting/SysTableConfig.cshtml
@{
    ViewData["Title"] = "表配置";
}

@await Component.InvokeAsync("Form", new { tablename = "systableconfig", paneltitle = "表格配置,表单配置" })

<partial name="_BaseViewPartial" />

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Setting/SysUser.cshtml
@{
    ViewData["Title"] = "用户管理";
}

@await Component.InvokeAsync("Form", new { tablename = "sysuser", modalsize = 2 })

<partial name="_BaseViewPartial" />