src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Components/ButtonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;

namespace Netnr.ResponseFramework.ViewComponents
{
    public class ButtonViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            string current_url = "/" + RouteData.Values["controller"]?.ToString() + "/" + RouteData.Values["action"]?.ToString();

            //按钮列表
            var listBtn = new List<Domain.SysButton>();

            //根据路由反查页面对应的菜单
            var moMenu = Func.Common.QuerySysMenuList(x => x.Url == current_url).FirstOrDefault();
            if (moMenu != null)
            {
                //登录用户的角色信息
                var luri = Func.Common.LoginUserRoleInfo(HttpContext);
                if (luri != null && !string.IsNullOrWhiteSpace(luri.Buttons))
                {
                    //角色配置的按钮
                    var joRole = JObject.Parse(luri.Buttons);
                    //根据菜单ID取对应的按钮
                    string btns = joRole[moMenu.Id].ToStringOrEmpty();
                    if (!string.IsNullOrWhiteSpace(btns))
                    {
                        var btnids = btns.Split(',').ToList();

                        //根据按钮ID取按钮
                        listBtn = Func.Common.QuerySysButtonList(x => btnids.Contains(x.Id));
                    }
                }
            }

            return View(listBtn);
        }
    }
}

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_BaseViewPartial.cshtml
<!--列表-->
<div class="row">
    <div class="col-md-12">
        <div id="PGrid1" class="gridedit">
            <div id="Grid1" class="loadingimg"></div>
        </div>
    </div>
</div>

<!--配置表格-->
<script src="/js/inlay/configtable.js" asp-append-version="true"></script>
<!--配置表单-->
<script src="/js/inlay/configform.js" asp-append-version="true"></script>
<!--搜索模块-->
<script src="/js/inlay/configquery.js" asp-append-version="true"></script>
<!--引入页面JS-->
<script src='/js/@ViewContext.RouteData.Values["controller"].ToString()/@(ViewContext.RouteData.Values["action"].ToString()+".js")' asp-append-version="true"></script>

<script>
    //绑定数据
    setTimeout(z.FormAttrAjax, 0);

    //新增
    z.button("add", function () {
        //重置
        z.FormRequired('reset');
        //清空
        z.FormClear();
    });
    //编辑
    z.button("edit", function () {
        z.FormRequired('reset');
    });
    //查看
    z.button("see", function () {
        z.FormRequired('reset');
    });
    //导出
    $('#m_Export').click(function () {
        window.open('/io/export?uri=' + z.TableName);
    });
</script>

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="X-UA-Compatible" content="chrome=1,IE=edge" />
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <title>@ViewData["Title"] netnrf响应式框架</title>

    <!-- Bootstrap、字体 -->
    <link href="https://lib.baomitu.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://lib.baomitu.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- jQuery、Bootstrap -->
    <script src="https://lib.baomitu.com/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://lib.baomitu.com/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- EasyUI -->
    <link href="/lib/jquery-easyui-1.6.4/themes/default/easyui-custom.css" rel="stylesheet" asp-append-version="true" />
    <script src="/lib/jquery-easyui-1.6.4/jquery.easyui.min.js" asp-append-version="true"></script>

    <!-- DateTime -->
    <link href="/lib/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" asp-append-version="true" />
    <script src="/lib/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js" asp-append-version="true"></script>

    <!--页面自定义样式||重写-->
    <link href="/css/z.css" rel="stylesheet" asp-append-version="true" />
    <script src="/js/z.js" asp-append-version="true"></script>
</head>
<body>
    <div class="container-fluid">
        @await Component.InvokeAsync("Button")
        <div id="myBody">
            @RenderBody()
        </div>
    </div>
</body>
</html>

src/v2.1/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_LoadingPartial.cshtml
<div id="LoadingMask" style="position: fixed; top: 0; left: 0; bottom: 0; right: 0; background-color: white; z-index: 9999; background-image:url('/images/loading.gif');background-repeat:no-repeat;background-position:48% 45%"></div>